### ISSUE TITLE
got some errors..

### ISSUE THREAD

**Issue by scotch123** [cyberstruggle/L4sh#4]
[*] Started http server on 9999
[*] Started LDAP server on 1389
[*] Spraying 81 known HTTP Header
Traceback (most recent call last):
  File "main.py", line 243, in <module>
    main()
  File "main.py", line 240, in main
    get_a_life(target_options)
  File "main.py", line 199, in get_a_life
    spray_headers(target_options,command,args)
  File "main.py", line 128, in spray_headers
    go_clutch(url=url,method=request_method,data=None,headers=additionalrequest_headers)
  File "main.py", line 51, in go_clutch
    request_data.update(data)
TypeError: 'NoneType' object is not iterable

What's the problem ? :/

**Comment by safebuffer** [comment]
the issue already fixed you need to repull the repo
